# Usage : docker stack deploy -c postgres.stack.yml pgSQL

# 各 service 的 ZOO_MY_ID 不能相同，指定部署节点
version: "3"

networks:
    gb-net:
        external: true

services:
    pg_d1:
        image: hub:5000/gb-postgres:9.6.2 
        networks:
            - gb-net
        deploy:
            placement:
                constraints:
                    # 部署在指定的节点
                    - node.hostname == D1
            restart_policy:
                    condition: on-failure
        volumes:
            -
                /var/gb/data/pg/pg_sites01/:/var/data/ 

    pg_d2:
        image: hub:5000/gb-postgres:9.6.2 
        networks:
            - gb-net
        deploy:
            placement:
                constraints:
                    # 部署在指定的节点
                    - node.hostname == D2
            restart_policy:
                    condition: on-failure
        volumes:
            -
                /var/gb/data/pg/pg_sites02/:/var/data/ 

    pg_d3:
        image: hub:5000/gb-postgres:9.6.2 
        networks:
            - gb-net
        deploy:
            placement:
                constraints:
                    # 部署在指定的节点
                    - node.hostname == D3
            restart_policy:
                    condition: on-failure
        volumes:
            -
                /var/gb/data/pg/pg_sites03/:/var/data/ 

